groups:
  - name: cryptopay-alerts
    rules:
      - alert: CoreApiErrorRateHigh
        expr: increase(core_api_error_total[5m]) > 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Core API error rate is high

      - alert: PayoutOrchestratorErrorRateHigh
        expr: increase(payout_orchestrator_error_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Payout orchestrator error rate is high

      - alert: ReconciliationWorkerErrors
        expr: increase(reconciliation_worker_error_total[15m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Reconciliation worker returned errors

      - alert: OffshoreCollectorErrors
        expr: increase(offshore_collector_error_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Offshore collector error rate is high
