openapi: 3.0.3
info:
  title: CryptoPay Payout Orchestrator API
  version: 1.0.0
servers:
  - url: http://localhost:3003
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          type: object
          required: [code, message, requestId]
          properties:
            code: { type: string }
            message: { type: string }
            requestId: { type: string }
            details: {}
    InitiatePayoutRequest:
      type: object
      required: [transferId, method, recipientAccountRef, amountEtb, idempotencyKey]
      properties:
        transferId: { type: string }
        method:
          type: string
          enum: [bank]
        recipientAccountRef: { type: string }
        amountEtb:
          type: number
          minimum: 0
        idempotencyKey: { type: string }
paths:
  /healthz:
    get:
      responses:
        '200':
          description: OK
  /readyz:
    get:
      responses:
        '200':
          description: Ready
  /internal/v1/payouts/initiate:
    post:
      security:
        - bearerAuth: []
      parameters:
        - name: idempotency-key
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiatePayoutRequest'
      responses:
        '202':
          description: Payout initiated
        '400':
          description: Validation or idempotency error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
